name: Configuration Check
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Name?'
        default: 'World'
        required: true
  repository_dispatch:
    types:
      - configuration-check
jobs:
  check:
    name: Run check
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Say hello
        run: echo Hello!
      - name: print Payload
        run: '${toJson(github.event.client_payload}'
